Repository 5ruzo/bookly, pull requests merged in 2025-03, with the labels that each got.

#12 chore:#11 로컬 경로를 모두 허용하도록 pathname 수정
  next.config.mjs
Labels: 📜Chore

#14 chore:#13 tailwind.config 수정
  src/app/global-style.css
  tailwind.config.ts
Labels: 📜Chore

#15 chore:#13 tailwind.config 수정
  .prettierrc
  tailwind.config.ts
Labels: 📜Chore

#17 Feature/#2 layout
  package.json
  pnpm-lock.yaml
  public/images/.gitkeep
  public/images/logo.png
  src/app/layout.tsx
  src/components/layouts/.gitkeep
  src/components/layouts/footer.tsx
  src/components/layouts/header-dropdown-menu.tsx
  src/components/layouts/header.tsx
  src/components/ui/dropdown-menu.tsx
  src/types/layout.type.ts
Labels: 🔧Feature, 💐Style

#30 fix:#28 반환 타입 추가
  src/lib/utils/common.util.ts
Labels: 👨‍🔧Fix

#27 Feature/#5 cart page UI
  package.json
  pnpm-lock.yaml
  src/app/cart/page.tsx
  src/components/features/cart/book-summary.tsx
  src/components/features/cart/cart-table.tsx
  src/components/features/cart/cart.tsx
  src/components/features/cart/empty-cart.tsx
  src/components/features/cart/price-summary.tsx
  src/components/features/common/data-table.tsx
  src/components/ui/button.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/table.tsx
  src/types/cart/cart.type.ts
Labels: 🔧Feature, 💐Style, 📁Add

#36 Feature/#4 메인 페이지 구현
  src/components/ui/book-card.tsx
  src/components/ui/book-carousel-layout.tsx
  src/lib/api/common.api.ts
  src/lib/queries/use-get-books-by-bestseller-query.ts
  src/types/common.type.ts
Labels: 🏠Refactor

#39 Feature/#23 cart page
  src/app/cart/page.tsx
  src/components/features/cart/cart-table.tsx
  src/components/features/cart/cart-table/book-summary.tsx
  src/components/features/cart/cart-table/cart-check-book.tsx
  src/components/features/cart/cart-table/cart-table.columns.tsx
  src/components/features/cart/cart-table/cart-table.tsx
  src/components/features/cart/cart-table/quantity-control.tsx
  src/components/features/cart/cart-table/total-price.tsx
  src/components/features/cart/cart.tsx
  src/components/features/cart/empty-cart.tsx
  src/components/features/cart/price-summary.tsx
  src/constants/common.constant.ts
  src/constants/quantity-control-constant.ts
  src/lib/hooks/use-quantity-control.ts
  src/lib/utils/cart.utils.ts
  src/store/cart/cart-store.ts
Labels: 🔧Feature, 📁Add

#37 Feature/#4 메인 페이지 구현
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
  src/components/features/home/home-main-carousel-container.tsx
  src/components/features/home/home-main-carousel.tsx
  src/components/features/home/home-strip-banners-carousel.tsx
  src/components/ui/best-seller-carousel.tsx
  src/components/ui/book-carousel-layout.tsx
  src/components/ui/recommened-books-carousel.tsx
  src/constants/common.constant.ts
  src/constants/home.constant.ts
  src/lib/api/common.api.ts
  src/lib/api/home.api.ts
  src/lib/queries/use-get-images-by-main-carousel.ts
  src/lib/queries/use-get-images-by-strip-banners.ts
  src/types/home.type.ts
Labels: 🔧Feature

#38 Feature/#8 mypage like list
  src/app/my-page/layout.tsx
  src/app/my-page/like-list/page.tsx
  src/app/my-page/order-details/page.tsx
  src/components/features/my-page/my-page-side-bar.tsx
Labels: 🔧Feature, 💐Style

#43 Style/#3 detail page UI
  src/app/detail/[id]/page.tsx
  src/app/global-style.css
  src/components/features/detail/button-area/detail-like-button.tsx
  src/components/features/detail/detail-button-area.tsx
  src/components/features/detail/detail-product-info.tsx
  src/components/features/detail/detail-quantity-input.tsx
  src/components/features/detail/detail-rating.tsx
  src/components/ui/button.tsx
  src/constants/detail.constans.ts
  src/lib/api/detail.api.ts
  src/lib/utils/detail.util.ts
  src/types/detail.type.ts
  tailwind.config.ts
Labels: 🔧Feature, 💐Style

#45 Feature/#24 order page
  package.json
  pnpm-lock.yaml
  src/app/api/toss/route.ts
  src/app/cart/page.tsx
  src/app/order/fail/page.tsx
  src/app/order/page.tsx
  src/app/order/success/page.tsx
  src/components/features/cart/cart-table/quantity-control.tsx
  src/components/features/cart/cart.tsx
  src/components/features/cart/price-summary.tsx
  src/components/features/order/delivery-form.tsx
  src/components/features/order/delivery-info.tsx
  src/components/features/order/form-field.tsx
  src/components/features/order/order-info.tsx
  src/components/features/order/toss-payments.tsx
  src/constants/common.constant.ts
  src/constants/quantity-control.constant.ts
  src/lib/hooks/order/delivery-form-hook.ts
  src/lib/hooks/order/toss-payments-hook.ts
  src/lib/hooks/use-quantity-control.ts
  src/lib/utils/cart.utils.ts
  src/lib/utils/common.util.ts
  src/store/cart/cart-store.ts
  src/types/order/order.type.ts
Labels: 🔧Feature, 📁Add

#47 bugfix:#24 결제 실패 페이지 'use client' 추가
  src/app/order/fail/page.tsx
Labels: 🕷️BugFix

#51 bugfix:#4 lint 오류 해결
  src/components/features/home/home-main-carousel.tsx
  src/components/features/home/home-strip-banners-carousel.tsx
Labels: 🕷️BugFix

#44 Feature/#9 mypage order details
  src/app/my-page/order-details/page.tsx
  src/components/features/my-page/order-detail-card.tsx
  src/constants/my-page.constant.ts
  src/lib/api/my-page.api.ts
  src/lib/utils/my-page.util.ts
  src/types/my-page.type.ts
Labels: 💐Style

#56 Feature/#4 메인 페이지 구현
  src/components/features/home/home-strip-banners-carousel.tsx
  src/components/ui/best-seller-carousel.tsx
  src/components/ui/recommened-books-carousel.tsx
  src/components/ui/skeletod-card.tsx
  src/components/ui/skeleton.tsx
  src/lib/api/home.api.ts
  src/lib/queries/use-get-images-by-main-carousel.ts
Labels: 🏠Refactor

#60 Feature/#52 주문 내역 DB 추가
  src/app/order/page.tsx
  src/app/order/success/page.tsx
  src/components/features/cart/book-summary.tsx
  src/components/features/cart/cart-check-book.tsx
  src/components/features/cart/cart-table.columns.tsx
  src/components/features/cart/cart-table.tsx
  src/components/features/cart/cart.tsx
  src/components/features/cart/quantity-control.tsx
  src/components/features/cart/total-price.tsx
  src/components/features/order/delivery-form.tsx
  src/components/features/order/form-field.tsx
  src/components/features/order/order-form.tsx
  src/components/features/order/toss-payments.tsx
  src/components/ui/data-table.tsx
  src/lib/api/order-api.ts
  src/lib/hooks/order/delivery-form-hook.ts
  src/lib/hooks/order/toss-payments-hook.ts
  src/lib/utils/cart.utils.ts
  src/store/cart/cart-store.ts
  src/types/cart.type.ts
  src/types/order.type.ts
Labels: 🔧Feature, 📁Add

#63 Refactor/#54 auth page refactor
  src/app/auth/forgot-password/page.tsx
  src/app/auth/reset-password/page.tsx
  src/app/auth/sign-in/page.tsx
  src/app/auth/sign-up/page.tsx
  src/components/features/auth/auth-button.tsx
  src/components/features/auth/auth-card.tsx
  src/components/features/auth/auth-error-message.tsx
  src/components/features/auth/auth-input.tsx
  src/components/features/auth/auth-link.tsx
  src/components/features/cart/quantity-control.tsx
  src/lib/api/auth-service.ts
  src/lib/api/order-api.ts
  src/lib/utils/auth.util.ts
  src/types/auth.type.ts
Labels: 🏠Refactor

#65 Bugfix/#64 book id type
  src/components/features/cart/cart-check-book.tsx
  src/components/features/cart/cart-table.tsx
  src/components/features/cart/cart.tsx
  src/components/features/cart/price-summary.tsx
  src/components/features/detail/detail-button-area.tsx
  src/components/features/order/order-form.tsx
  src/components/features/order/order-info.tsx
  src/constants/common.constant.ts
  src/lib/api/order-api.ts
  src/lib/hooks/use-quantity-control.ts
  src/store/cart-store.ts
  src/types/cart.type.ts
  src/types/order.type.ts
Labels: 👨‍🔧Fix

#68 refactor:#4 common.api 에 supabase client 사용
  src/lib/api/common.api.ts
Labels: 🏠Refactor

#69 Bugfix/#53 cart page calculator
  src/components/features/cart/cart-check-book.tsx
  src/components/features/cart/cart-table.tsx
  src/components/features/cart/cart.tsx
  src/components/features/cart/quantity-control.tsx
  src/components/features/detail/detail-button-area.tsx
  src/components/ui/book-card.tsx
  src/lib/utils/cart.utils.ts
  src/store/cart-store.ts
Labels: 🕷️BugFix

#75 fix:#74 로그인 텍스트가 공간을 차지하도록 수정
  src/components/layouts/header-dropdown-menu.tsx
Labels: 💐Style, 👨‍🔧Fix

#76 fix:#74 로그아웃 텍스트 동일하게 수정
  src/components/layouts/header-dropdown-menu.tsx
Labels: 💐Style, 👨‍🔧Fix

#79 bugfix:#78 - 체크한 상품이 없을 경우 주문 페이지로 이동 블락 처리
  src/components/features/cart/cart.tsx
  src/components/features/order/order-info.tsx
Labels: 🕷️BugFix

#83 Bugfix/#81 비회원 장바구니 막기
  src/app/auth/sign-in/page.tsx
  src/app/auth/sign-up/page.tsx
  src/components/features/detail/button-area/detail-like-button.tsx
  src/components/features/detail/detail-button-area.tsx
  src/components/layouts/header.tsx
  src/components/ui/book-card.tsx
Labels: 🕷️BugFix

#92 fix:#90 찜 목록 바텀 마진
  src/components/features/my-page/like-list-area.tsx
Labels: 💐Style, 🕷️BugFix

#99 fix:#98 fix mypage responsive
  src/components/features/my-page/like-list-area.tsx
  src/components/features/my-page/order-detail-card.tsx
Labels: 💐Style, 👨‍🔧Fix

#100 Docs/#57 readme 작성
  README.md
Labels: 👨‍🔧Fix

#101 docs:#57 배포 주소 추가
  README.md
Labels: 👨‍🔧Fix
